import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar1 from "@/component/Navbar1";
import Navbar2 from "@/component/Navbar2";
import Image1 from "@/component/Image";
import BuyerNavbar from "@/component/BuyerNavbar";
import SellerNavbar from "@/component/SellerNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar1/>
        <Navbar2/>
        <Image1/>
        <BuyerNavbar/>
        <SellerNavbar/>
        <br/>
        {children}
      </body>
    </html>
  );
}
